language: cpp
before_script:
  - sudo apt-get install -y libboost-test-dev
  - sudo apt-get install -y cmake libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
script:
  - cd $TRAVIS_BUILD_DIR
  - cmake helloworld
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T helloworld-$TRAVIS_BUILD_NUMBER-Linux.deb 
    -ucyrilarcher:$BINTRAY_API_KEY
    "https://api.bintray.com/content/none108/otus-cpp/helloworld/$TRAVIS_BUILD_NUMBER/helloworld-$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"