language: cpp
before_script:
  - sudo apt-get install -y libboost-test-dev
  - sudo apt-get install -y cmake libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
script:
  - cd $TRAVIS_BUILD_DIR
  - cmake helloworld
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package