language: cpp
before_script:
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo make install
script:
  - cd $TRAVIS_BUILD_DIR/ip_filter
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T ip_filter-$TRAVIS_BUILD_NUMBER-Linux.deb -ucyrilar4er:$BINTRAY_API_KEY "https://api.bintray.com/content/cyrilar4er/otus-cpp/ip_filter/$TRAVIS_BUILD_NUMBER/ip_filter-$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"